version: '2'
services:
    prep_18-app:
        image: prep_18
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://prep_18-mysql:3306/prep_18?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prep_18-mysql:
        extends:
            file: mysql.yml
            service: prep_18-mysql
